### ISSUE TITLE
'LegacyVersion' object has no attribute 'major' on current 3.3.x branch

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/QGISGeoNodePlugin#247]
If trying to connect to a recent 3.3.x branch GeoNode instance like `https://stable.demo.geonode.org` the plugin connection widget will fail with:

```
AttributeError: 'LegacyVersion' object has no attribute 'major' 
Traceback (most recent call last):
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\connection_dialog.py", line 184, in handle_discovery_test
    self.update_connection_details()
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\connection_dialog.py", line 231, in update_connection_details
    client: BaseGeonodeClient = apiclient.get_geonode_client(current_settings)
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 13, in get_geonode_client
    class_path = select_client_class_path(connection_settings.geonode_version)
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 24, in select_client_class_path
    if geonode_version.major == 4:
AttributeError: 'LegacyVersion' object has no attribute 'major'
```

This likely is caused by the non-formal version string displayed, eg. here:

https://stable.demo.geonode.org/version.txt

**Comment by gannebamm** [comment]
The current master.demo.geonode.org instance does work with the plugin. The error above seems to be specific to the 3.3.x branch or parts of it.

**Comment by Fifoterra** [comment]
It also happens with Geonode 4.0 for QGIS 3.26 and QGIS 3.22.

**Comment by Cornacap** [comment]
It also happens with my configuration (QGis 3.22, Geonode 4.0) and Hosting in our intranet.

**Comment by timlinux** [comment]
It seems the error only gets raised if you paste the URL with the default # that GeoNode adds to the end of the base URL:

![image](https://github.com/GeoNode/QGISGeoNodePlugin/assets/178003/b61f8655-35c4-4686-aba9-6e562a2a1793)


Removing that should resolve the issue:

![image](https://github.com/GeoNode/QGISGeoNodePlugin/assets/178003/e17c7d7e-05cb-4165-a243-be203ad0f031)

**Comment by vidlb** [comment]
Same here using latest plugin and geonode 4.1.3, this occurs only when testing connection

**Comment by gannebamm** [comment]
should be fixed with https://github.com/GeoNode/QGISGeoNodePlugin/pull/271
