### ISSUE TITLE
GeoNode plugin causes errors when opening layer properties

### ISSUE THREAD

**Issue by gubuntu** [GeoNode/QGISGeoNodePlugin#262]
Screenshot - note misplacement of GeoNode elements

![image](https://github.com/GeoNode/QGISGeoNodePlugin/assets/496911/c03beb43-01b5-4f0d-b6fb-ae291d35a72d)

Stack trace

```
2023-07-12T11:18:21 	WARNING    Traceback (most recent call last):
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_maplayer_config_widget_factory.py", line 18, in createWidget
              return GeonodeMapLayerConfigWidget(layer, canvas, parent)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 101, in __init__
              suitable_connections = self._get_suitable_upload_connections()
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 411, in _get_suitable_upload_connections
              client: typing.Optional[base.BaseGeonodeClient] = get_geonode_client(
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 13, in get_geonode_client
              class_path = select_client_class_path(connection_settings.geonode_version)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 24, in select_client_class_path
              if geonode_version.major == 4:
             AttributeError: 'LegacyVersion' object has no attribute 'major'
             
2023-07-12T11:18:30 	WARNING    Traceback (most recent call last):
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_maplayer_config_widget_factory.py", line 18, in createWidget
              return GeonodeMapLayerConfigWidget(layer, canvas, parent)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 101, in __init__
              suitable_connections = self._get_suitable_upload_connections()
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 411, in _get_suitable_upload_connections
              client: typing.Optional[base.BaseGeonodeClient] = get_geonode_client(
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 13, in get_geonode_client
              class_path = select_client_class_path(connection_settings.geonode_version)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 24, in select_client_class_path
              if geonode_version.major == 4:
             AttributeError: 'LegacyVersion' object has no attribute 'major'
             
2023-07-12T11:24:55 	WARNING    Traceback (most recent call last):
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_maplayer_config_widget_factory.py", line 18, in createWidget
              return GeonodeMapLayerConfigWidget(layer, canvas, parent)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 101, in __init__
              suitable_connections = self._get_suitable_upload_connections()
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 411, in _get_suitable_upload_connections
              client: typing.Optional[base.BaseGeonodeClient] = get_geonode_client(
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 13, in get_geonode_client
              class_path = select_client_class_path(connection_settings.geonode_version)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 24, in select_client_class_path
              if geonode_version.major == 4:
             AttributeError: 'LegacyVersion' object has no attribute 'major'
             
2023-07-12T11:26:59 	WARNING    Traceback (most recent call last):
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_data_source_widget.py", line 307, in activate_connection_configuration
              self.api_client = get_geonode_client(current_connection)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 13, in get_geonode_client
              class_path = select_client_class_path(connection_settings.geonode_version)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 24, in select_client_class_path
              if geonode_version.major == 4:
             AttributeError: 'LegacyVersion' object has no attribute 'major'
             
2023-07-12T11:39:31 	WARNING    Traceback (most recent call last):
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_maplayer_config_widget_factory.py", line 18, in createWidget
              return GeonodeMapLayerConfigWidget(layer, canvas, parent)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 101, in __init__
              suitable_connections = self._get_suitable_upload_connections()
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_map_layer_config_widget.py", line 411, in _get_suitable_upload_connections
              client: typing.Optional[base.BaseGeonodeClient] = get_geonode_client(
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 13, in get_geonode_client
              class_path = select_client_class_path(connection_settings.geonode_version)
              File "C:\Users/Faridah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 24, in select_client_class_path
              if geonode_version.major == 4:
             AttributeError: 'LegacyVersion' object has no attribute 'major'
```

QGIS info

```
QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
qgis_geonode
1.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

```

**Comment by giohappy** [comment]
@gubuntu We are fixing several issues for the upcoming release of the plugin, but we have never seen the problem you're reporting. Notice that the minimum QGIS version for the plugin will be 3.34, the current LTS. Could you try with this version?
