### ISSUE TITLE
Error Complemento Qgis GeoNode

### ISSUE THREAD

**Issue by Mechysvic** [GeoNode/QGISGeoNodePlugin#266]
Estoy recibiendo este error cada vez que quiero conectarme a geonode: 
AttributeError: 'LegacyVersion' object has no attribute 'major' 
Traceback (most recent call last):
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\connection_dialog.py", line 184, in handle_discovery_test
    self.update_connection_details()
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\connection_dialog.py", line 231, in update_connection_details
    client: BaseGeonodeClient = apiclient.get_geonode_client(current_settings)
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 13, in get_geonode_client
    class_path = select_client_class_path(connection_settings.geonode_version)
  File "C:\Users/hoedt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\__init__.py", line 24, in select_client_class_path
    if geonode_version.major == 4:
AttributeError: 'LegacyVersion' object has no attribute 'major'

Gracias!

**Comment by giohappy** [comment]
Fixed in #289
