### ISSUE TITLE
Handling future GeoNode version 5

### ISSUE THREAD

**Issue by Gpetrak** [GeoNode/QGISGeoNodePlugin#278]
Currently the plugin cannot not recognize a version above 4, (e.g 5.0.0) and if a version is above 4 it uses the old API client: GeonodeLegacyApiClient

Thus, if we define a connection on GeoNode development demo which is under the version 5.0.0, while the `Test Connection` functionality works, it raises a 404 error when we try to search and load the available layers:

```bash
Error: Error transferring https://development.demo.geonode.org/api/layers/?limit=10&offset=0&type__in=vector&type__in=raster&order_by=title - server replied: Not Found
```

![Screenshot from 2024-10-31 13-14-45](https://github.com/user-attachments/assets/0c622c43-cea9-46b3-b03c-66674f08a39e)

We need to update the apiclient.__init__.py file in order to use the same client (at least for now) as for the versions > 4.2 and check if it works.

**Comment by giohappy** [comment]
Let's fix it @Gpetrak

**Comment by giohappy** [comment]
As agreed, we will fo the following:

 - remove support for GeoNode < 4
 - rename the module to follow the GeoNode API version naming (v2 at the moment)
 - increase the supported GeoNode version, to allow using the next GeoNode 5 (master branch)

In the future we will only rely on the API version, but at the moment we don't have an a way to know which API a GeoNode instance supports, except trying using the endpoints...

**Comment by smallvalthoss** [comment]
hey @Gpetrak, do you know what version [stable.demo.geonode.org](https://stable.demo.geonode.org/) is? It seems I can connect to it with the qgis plugin, but using 4.4.x doesn't seem to work on my end when I host it.

**Comment by Gpetrak** [comment]
Hi @smallvalthoss . The GeoNode stable demo, uses the version: `4.4.0.dev0`. What is the error / problem that you have with the plugin ?

**Comment by smallvalthoss** [comment]
Hey @Gpetrak, thanks for the reply. Here is what I'm having trouble with:

# Uploads:
getting url error:
![image](https://github.com/user-attachments/assets/95b7e029-23af-4dc1-8db0-6658f50ca1d3)

note that this does upload successfully, but it gives me this error. Not certain why.

# WFS/WMS
Under Layer -> Data Source Manager -> Geonode Plugin, I am able to search the layers (awesome). However, when i click load layer via wms/wfs, I get the following stack trace:

`Traceback (most recent call last):
  File "C:\Users/ostrandw7276/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\geonode_v3.py", line 159, in handle_dataset_detail
    dataset = self._parse_dataset_detail(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ostrandw7276/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\geonode_v3.py", line 405, in _parse_dataset_detail
    metadata_author=raw_dataset.get("metadata_author", {}).get("username", ""),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'`

**Comment by Gpetrak** [comment]
Hi @smallvalthoss . Both errors have been fixed and the master branch has been updated. We will release a new version soon, which will be available through the QGIS.

**Comment by desilvarami** [comment]
Hi @Gpetrak , Have you released the new version as mentioned above.  My GeoNode is version 4.4.1 and I am getting the very same error when trying to load a wms/wfs layer through the plugin. Same error for Stable demo as well.
I have reinstalled the QGIS GeoNode plugin and tried but no difference.
